net_model: AttentionUnet3D
torch_model_path: ./work/AttentionUnet3D-nerve-pruned-0.758-CT_NerveSeg_v1.1.1.pth
onnx_model_path: ./work/AttentionUnet3D-nerve-pruned-0.758-CT_NerveSeg_v1.1.1.onnx
trt_model_path: ./work/AttentionUnet3D-nerve-pruned-0.758-CT_NerveSeg_v1.1.1.trt
task: onnx2trt # torch2onnx or onnx2trt or torch2trt
use_verify: True
use_fp16: False
batch_size: 1
in_ch: 1
num_classes: 1
input_shape: !!python/tuple [64, 288, 288]
is_pruned: True









